const recruitmentFields = {
  province: null,
  employeeCountLabel: null,
  careersUrl: "https://test.nl/werken-bij",
  vacancyPageUrl: null,
  generalEmail: "info@test.nl",
  hrEmail: "hr@test.nl",
  kvkNumber: null,
  aiSummary: null,
};

export const baseTestCandidate = {
  externalId: "test:1",
  name: "Test BV",
  normalizedName: "test",
  website: "https://test.nl",
  domain: "test.nl",
  linkedinUrl: "https://linkedin.com/company/test",
  email: "info@test.nl",
  phone: "+31 20 1234567",
  city: "Amsterdam",
  region: "Noord-Holland",
  country: "NL",
  sector: "Software en SaaS",
  employeeCountMin: 11,
  employeeCountMax: 50,
  description: null,
  source: "brave-web-search",
  sourceUrl: null,
  vacancyCount: 2,
  vacancyTitles: ["HR-medewerker", "Office Manager"],
  hiringSignals: [
    { type: "vacancy", description: "HR vacature", source: "Indeed", confidence: 0.8 },
    { type: "careers_page", description: "Werken bij pagina", source: "Website", confidence: 0.75 },
  ],
  confidence: 0.8,
  discoveredAt: new Date().toISOString(),
  lastVerifiedAt: null,
  ...recruitmentFields,
};
