export {
  archiveVacancyInputSchema,
  createVacancyInputSchema,
  getVacancyInputSchema,
  listVacanciesInputSchema,
  searchVacanciesInputSchema,
  updateVacancyInputSchema,
  updateVacancyToolParametersSchema,
  type UpdateVacancyToolParametersDto,
  type ArchiveVacancyInputDto,
  type CreateVacancyInputDto,
  type GetVacancyInputDto,
  type ListVacanciesInputDto,
  type SearchVacanciesInputDto,
  type UpdateVacancyInputDto,
} from "./vacancy.schemas";
